### ISSUE TITLE
Yeni SHABLON Razilashmasi

### ISSUE THREAD

**Issue by ramin19950227** [ramin19950227/SaleSoft#56]
Bele bir qerara Geldim Proqramda Umimi anlayish olmalidir
Meselen Butun Classlarda TextField-ler ve Labeller Metodlar eyni qayda ile adlandirilmalidir
meselen bir Controllerde (imageViewBarCode)- adlanir
Digerinde ise (bTF) adlanir
Artiq Butun Class-larda (Declaration Group) - Formasinda yazacam
yani Elanlari Cemleyecem bir setire ve adlandirma En qisa Formada Olacaq
- Siz Ne deyirsiz? @teyyub ??
@FXML
private TextField bTF, nTF, qTF; ... ve saileri
bTF = barCodeTextField

**Comment by teyyub** [comment]
əgər mümkündürsə edə bilərsən

**Comment by ramin19950227** [comment]
Super Teshekkur
